"""CF2-02: import batches (ImportBatch)

Revision ID: 037a2c3a997e
Revises: cae49f73ed41
Create Date: 2026-09-15 19:20:27.540200
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "037a2c3a997e"
down_revision = "cae49f73ed41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("household_id", sa.String(length=80), nullable=False),
        sa.Column("account_id", sa.String(length=80), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("source_kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("column_mapping", sa.JSON(), nullable=False),
        sa.Column("header_row", sa.Integer(), nullable=False),
        sa.Column("separator", sa.String(length=4), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("invalid_rows", sa.Integer(), nullable=False),
        sa.Column("rows", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source_kind IN ('csv','excel')", name="ck_import_batch_source_kind"),
        sa.CheckConstraint(
            "status IN ('parsed','validated','confirmed','cancelled')",
            name="ck_import_batch_status",
        ),
        sa.CheckConstraint("invalid_rows >= 0", name="ck_import_batch_invalid_rows_nonnegative"),
        sa.CheckConstraint("total_rows >= 0", name="ck_import_batch_total_rows_nonnegative"),
        sa.CheckConstraint("valid_rows >= 0", name="ck_import_batch_valid_rows_nonnegative"),
        sa.ForeignKeyConstraint(["account_id"], ["financial_accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_batches_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_import_batches_household_id"), ["household_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_batches_household_id"))
        batch_op.drop_index(batch_op.f("ix_import_batches_account_id"))

    op.drop_table("import_batches")
    # ### end Alembic commands ###
