"""CF1-10, CF1-11 y CF1-09: deudas, cuotas y pagos de deuda

Revision ID: 409919e8d93a
Revises: 552e7d03349d
Create Date: 2026-09-15 18:15:36.147653
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "409919e8d93a"
down_revision = "552e7d03349d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "debts",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("household_id", sa.String(length=80), nullable=False),
        sa.Column("account_id", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("original_amount", sa.Integer(), nullable=False),
        sa.Column("current_balance", sa.Integer(), nullable=False),
        sa.Column("interest_rate", sa.Float(), nullable=False),
        sa.Column("minimum_payment", sa.Integer(), nullable=False),
        sa.Column("due_day", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','paid_off','closed')", name="ck_debt_status"),
        sa.CheckConstraint(
            "type IN ('credit_card','loan','auto','mortgage','line','other')", name="ck_debt_type"
        ),
        sa.CheckConstraint("current_balance >= 0", name="ck_debt_current_balance_nonnegative"),
        sa.CheckConstraint("due_day BETWEEN 1 AND 31", name="ck_debt_due_day"),
        sa.CheckConstraint("interest_rate >= 0", name="ck_debt_interest_rate_nonnegative"),
        sa.CheckConstraint("minimum_payment >= 0", name="ck_debt_minimum_payment_nonnegative"),
        sa.CheckConstraint("original_amount >= 0", name="ck_debt_original_amount_nonnegative"),
        sa.ForeignKeyConstraint(["account_id"], ["financial_accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_debts_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_debts_household_id"), ["household_id"], unique=False)

    op.create_table(
        "debt_payments",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("debt_id", sa.String(length=80), nullable=False),
        sa.Column("account_id", sa.String(length=80), nullable=True),
        sa.Column("transaction_id", sa.String(length=80), nullable=True),
        sa.Column("recorded_by", sa.String(length=80), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("type IN ('ordinary','extraordinary')", name="ck_debt_payment_type"),
        sa.CheckConstraint("amount > 0", name="ck_debt_payment_amount_positive"),
        sa.ForeignKeyConstraint(["account_id"], ["financial_accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["debt_id"], ["debts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["recorded_by"], ["household_members.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("debt_payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_debt_payments_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_debt_payments_debt_id"), ["debt_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_debt_payments_payment_date"), ["payment_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_debt_payments_recorded_by"), ["recorded_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_debt_payments_transaction_id"), ["transaction_id"], unique=False
        )

    op.create_table(
        "installments",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("debt_id", sa.String(length=80), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("principal_amount", sa.Integer(), nullable=False),
        sa.Column("interest_amount", sa.Integer(), nullable=False),
        sa.Column("fee_amount", sa.Integer(), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('pending','paid','overdue')", name="ck_installment_status"),
        sa.CheckConstraint("fee_amount >= 0", name="ck_installment_fee_nonnegative"),
        sa.CheckConstraint("interest_amount >= 0", name="ck_installment_interest_nonnegative"),
        sa.CheckConstraint("principal_amount >= 0", name="ck_installment_principal_nonnegative"),
        sa.CheckConstraint(
            "total_amount = principal_amount + interest_amount + fee_amount",
            name="ck_installment_total",
        ),
        sa.ForeignKeyConstraint(["debt_id"], ["debts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("installments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_installments_debt_id"), ["debt_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_installments_due_date"), ["due_date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("installments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_installments_due_date"))
        batch_op.drop_index(batch_op.f("ix_installments_debt_id"))

    op.drop_table("installments")
    with op.batch_alter_table("debt_payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_debt_payments_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_debt_payments_recorded_by"))
        batch_op.drop_index(batch_op.f("ix_debt_payments_payment_date"))
        batch_op.drop_index(batch_op.f("ix_debt_payments_debt_id"))
        batch_op.drop_index(batch_op.f("ix_debt_payments_account_id"))

    op.drop_table("debt_payments")
    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_debts_household_id"))
        batch_op.drop_index(batch_op.f("ix_debts_account_id"))

    op.drop_table("debts")
    # ### end Alembic commands ###
