"""CF1-06 y CF1-07: categorias y fuentes de ingreso

Revision ID: 4a4c05c4ec6e
Revises: 73b3ed995ce9
Create Date: 2026-09-15 18:06:52.972101
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "4a4c05c4ec6e"
down_revision = "73b3ed995ce9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("household_id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('expense','income','transfer')", name="ck_category_kind"),
        sa.CheckConstraint("status IN ('active','inactive')", name="ck_category_status"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "name", "kind", name="uq_category_household_name_kind"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_household_id"), ["household_id"], unique=False
        )

    op.create_table(
        "income_sources",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("household_id", sa.String(length=80), nullable=False),
        sa.Column("member_id", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("expected_amount", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','inactive')", name="ck_income_source_status"),
        sa.CheckConstraint(
            "expected_amount >= 0", name="ck_income_source_expected_amount_nonnegative"
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["member_id"], ["household_members.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "name", name="uq_income_source_household_name"),
    )
    with op.batch_alter_table("income_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_income_sources_household_id"), ["household_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_income_sources_member_id"), ["member_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("income_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_income_sources_member_id"))
        batch_op.drop_index(batch_op.f("ix_income_sources_household_id"))

    op.drop_table("income_sources")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_household_id"))

    op.drop_table("categories")
    # ### end Alembic commands ###
