"""CF1-08: modelo de transacciones

Revision ID: 552e7d03349d
Revises: 4a4c05c4ec6e
Create Date: 2026-09-15 18:13:29.052034
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "552e7d03349d"
down_revision = "4a4c05c4ec6e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("account_id", sa.String(length=80), nullable=False),
        sa.Column("to_account_id", sa.String(length=80), nullable=True),
        sa.Column("category_id", sa.String(length=80), nullable=True),
        sa.Column("recorded_by", sa.String(length=80), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('posted','voided')", name="ck_transaction_status"),
        sa.CheckConstraint(
            "type <> 'transfer' OR to_account_id IS NOT NULL", name="ck_transfer_destination"
        ),
        sa.CheckConstraint(
            "type = 'transfer' OR to_account_id IS NULL", name="ck_transfer_source_only"
        ),
        sa.CheckConstraint(
            "type IN ('expense','income','transfer','payment','adjustment')",
            name="ck_transaction_type",
        ),
        sa.CheckConstraint("amount <> 0", name="ck_transaction_amount_nonzero"),
        sa.ForeignKeyConstraint(["account_id"], ["financial_accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recorded_by"], ["household_members.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["to_account_id"], ["financial_accounts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transactions_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_transactions_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_transactions_recorded_by"), ["recorded_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_to_account_id"), ["to_account_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_to_account_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_recorded_by"))
        batch_op.drop_index(batch_op.f("ix_transactions_date"))
        batch_op.drop_index(batch_op.f("ix_transactions_category_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_account_id"))

    op.drop_table("transactions")
    # ### end Alembic commands ###
