"""CF1-18 y CF1-19: planes de pago y escenarios de proyeccion

Revision ID: 5571f49c368e
Revises: b5b36c0b1a8b
Create Date: 2026-09-15 18:34:46.920502
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "5571f49c368e"
down_revision = "b5b36c0b1a8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_plans",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("household_id", sa.String(length=80), nullable=False),
        sa.Column("strategy", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','selected','archived')", name="ck_payment_plan_status"
        ),
        sa.CheckConstraint("strategy IN ('snowball','avalanche')", name="ck_payment_plan_strategy"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payment_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payment_plans_household_id"), ["household_id"], unique=False
        )

    op.create_table(
        "projection_scenarios",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("plan_id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("monthly_payment", sa.Integer(), nullable=False),
        sa.Column("extra_income", sa.JSON(), nullable=True),
        sa.Column("assumptions", sa.JSON(), nullable=True),
        sa.Column("result_summary", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "monthly_payment >= 0", name="ck_projection_monthly_payment_nonnegative"
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["payment_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projection_scenarios", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_projection_scenarios_plan_id"), ["plan_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projection_scenarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projection_scenarios_plan_id"))

    op.drop_table("projection_scenarios")
    with op.batch_alter_table("payment_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_plans_household_id"))

    op.drop_table("payment_plans")
    # ### end Alembic commands ###
