"""initial domain base

Revision ID: 73b3ed995ce9
Revises:
Create Date: 2026-09-15 18:00:00.155742
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "73b3ed995ce9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_institutions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','inactive')"),
        sa.CheckConstraint("type IN ('bank','fintech','store','other')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "households",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','paused','archived')"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "financial_accounts",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("household_id", sa.String(length=80), nullable=False),
        sa.Column("institution_id", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("balance_reported", sa.Integer(), nullable=False),
        sa.Column("balance_calculated", sa.Integer(), nullable=False),
        sa.Column("original_amount", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("currency = 'CLP'"),
        sa.CheckConstraint("status IN ('active','paused','closed')"),
        sa.CheckConstraint(
            "type IN ('checking','savings','credit_card','cash','wallet','loan_line')"
        ),
        sa.CheckConstraint("balance_calculated >= 0"),
        sa.CheckConstraint("balance_reported >= 0"),
        sa.CheckConstraint("original_amount IS NULL OR original_amount >= 0"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["financial_institutions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financial_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_financial_accounts_household_id"), ["household_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_financial_accounts_institution_id"), ["institution_id"], unique=False
        )

    op.create_table(
        "household_members",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("household_id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('admin','member')"),
        sa.CheckConstraint("status IN ('active','inactive')"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("household_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_household_members_household_id"), ["household_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("household_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_household_members_household_id"))

    op.drop_table("household_members")
    with op.batch_alter_table("financial_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financial_accounts_institution_id"))
        batch_op.drop_index(batch_op.f("ix_financial_accounts_household_id"))

    op.drop_table("financial_accounts")
    op.drop_table("households")
    op.drop_table("financial_institutions")
    # ### end Alembic commands ###
