"""CF1-12: presupuesto mensual (Budget y BudgetCategory)

Revision ID: b5b36c0b1a8b
Revises: 409919e8d93a
Create Date: 2026-09-15 18:17:42.399829
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "b5b36c0b1a8b"
down_revision = "409919e8d93a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("household_id", sa.String(length=80), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('draft','active','closed')", name="ck_budget_status"),
        sa.CheckConstraint("month BETWEEN 1 AND 12", name="ck_budget_month"),
        sa.CheckConstraint("year BETWEEN 2000 AND 2100", name="ck_budget_year"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "year", "month", name="uq_budget_household_period"),
    )
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_budgets_household_id"), ["household_id"], unique=False)

    op.create_table(
        "budget_categories",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("budget_id", sa.String(length=80), nullable=False),
        sa.Column("category_id", sa.String(length=80), nullable=False),
        sa.Column("planned_amount", sa.Integer(), nullable=False),
        sa.Column("actual_amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("actual_amount >= 0", name="ck_budget_category_actual_nonnegative"),
        sa.CheckConstraint("planned_amount >= 0", name="ck_budget_category_planned_nonnegative"),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("budget_id", "category_id", name="uq_budget_category"),
    )
    with op.batch_alter_table("budget_categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_budget_categories_budget_id"), ["budget_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_categories_category_id"), ["category_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("budget_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_categories_category_id"))
        batch_op.drop_index(batch_op.f("ix_budget_categories_budget_id"))

    op.drop_table("budget_categories")
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budgets_household_id"))

    op.drop_table("budgets")
    # ### end Alembic commands ###
