"""CF1-20: auditoria inmutable (audit_events)

Revision ID: cae49f73ed41
Revises: 5571f49c368e
Create Date: 2026-09-15 18:36:37.279486
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "cae49f73ed41"
down_revision = "5571f49c368e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("entity_kind", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=True),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_entity_kind"), ["entity_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_occurred_at"), ["occurred_at"], unique=False
        )

    op.execute(
        "CREATE TRIGGER audit_events_no_update "
        "BEFORE UPDATE ON audit_events FOR EACH ROW "
        "BEGIN SELECT RAISE(ABORT, 'audit_events is immutable'); END;"
    )
    op.execute(
        "CREATE TRIGGER audit_events_no_delete "
        "BEFORE DELETE ON audit_events FOR EACH ROW "
        "BEGIN SELECT RAISE(ABORT, 'audit_events is immutable'); END;"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_delete")
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_update")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_entity_kind"))
        batch_op.drop_index(batch_op.f("ix_audit_events_entity_id"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
